// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: detection.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchDetectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        [][]byte               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	FrameIds      []int64                `protobuf:"varint,2,rep,packed,name=frame_ids,json=frameIds,proto3" json:"frame_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDetectRequest) Reset() {
	*x = BatchDetectRequest{}
	mi := &file_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDetectRequest) ProtoMessage() {}

func (x *BatchDetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDetectRequest.ProtoReflect.Descriptor instead.
func (*BatchDetectRequest) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{0}
}

func (x *BatchDetectRequest) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *BatchDetectRequest) GetFrameIds() []int64 {
	if x != nil {
		return x.FrameIds
	}
	return nil
}

type BatchDetectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DetectResponse      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDetectResponse) Reset() {
	*x = BatchDetectResponse{}
	mi := &file_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDetectResponse) ProtoMessage() {}

func (x *BatchDetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDetectResponse.ProtoReflect.Descriptor instead.
func (*BatchDetectResponse) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{1}
}

func (x *BatchDetectResponse) GetResults() []*DetectResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type DetectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	FrameId       int64                  `protobuf:"varint,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectRequest) Reset() {
	*x = DetectRequest{}
	mi := &file_detection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectRequest) ProtoMessage() {}

func (x *DetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectRequest.ProtoReflect.Descriptor instead.
func (*DetectRequest) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{2}
}

func (x *DetectRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *DetectRequest) GetFrameId() int64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

type DetectResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VisualizedImage []byte                 `protobuf:"bytes,1,opt,name=visualized_image,json=visualizedImage,proto3" json:"visualized_image,omitempty"`
	OriginalImage   []byte                 `protobuf:"bytes,2,opt,name=original_image,json=originalImage,proto3" json:"original_image,omitempty"`
	Detections      []*DetectionMeta       `protobuf:"bytes,3,rep,name=detections,proto3" json:"detections,omitempty"`
	HasUncertain    bool                   `protobuf:"varint,4,opt,name=has_uncertain,json=hasUncertain,proto3" json:"has_uncertain,omitempty"`
	FrameId         int64                  `protobuf:"varint,5,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DetectResponse) Reset() {
	*x = DetectResponse{}
	mi := &file_detection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectResponse) ProtoMessage() {}

func (x *DetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectResponse.ProtoReflect.Descriptor instead.
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{3}
}

func (x *DetectResponse) GetVisualizedImage() []byte {
	if x != nil {
		return x.VisualizedImage
	}
	return nil
}

func (x *DetectResponse) GetOriginalImage() []byte {
	if x != nil {
		return x.OriginalImage
	}
	return nil
}

func (x *DetectResponse) GetDetections() []*DetectionMeta {
	if x != nil {
		return x.Detections
	}
	return nil
}

func (x *DetectResponse) GetHasUncertain() bool {
	if x != nil {
		return x.HasUncertain
	}
	return false
}

func (x *DetectResponse) GetFrameId() int64 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

type DetectionMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            float32                `protobuf:"fixed32,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            float32                `protobuf:"fixed32,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            float32                `protobuf:"fixed32,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            float32                `protobuf:"fixed32,4,opt,name=y2,proto3" json:"y2,omitempty"`
	Confidence    float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ClassId       int32                  `protobuf:"varint,6,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,7,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	IsUncertain   bool                   `protobuf:"varint,8,opt,name=is_uncertain,json=isUncertain,proto3" json:"is_uncertain,omitempty"`
	Entropy       float32                `protobuf:"fixed32,9,opt,name=entropy,proto3" json:"entropy,omitempty"`
	AnomalyScore  float32                `protobuf:"fixed32,10,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionMeta) Reset() {
	*x = DetectionMeta{}
	mi := &file_detection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionMeta) ProtoMessage() {}

func (x *DetectionMeta) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionMeta.ProtoReflect.Descriptor instead.
func (*DetectionMeta) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{4}
}

func (x *DetectionMeta) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *DetectionMeta) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *DetectionMeta) GetX2() float32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *DetectionMeta) GetY2() float32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

func (x *DetectionMeta) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectionMeta) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *DetectionMeta) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *DetectionMeta) GetIsUncertain() bool {
	if x != nil {
		return x.IsUncertain
	}
	return false
}

func (x *DetectionMeta) GetEntropy() float32 {
	if x != nil {
		return x.Entropy
	}
	return 0
}

func (x *DetectionMeta) GetAnomalyScore() float32 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_detection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{5}
}

func (x *ReloadRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

type ReloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadResponse) Reset() {
	*x = ReloadResponse{}
	mi := &file_detection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadResponse) ProtoMessage() {}

func (x *ReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadResponse.ProtoReflect.Descriptor instead.
func (*ReloadResponse) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{6}
}

func (x *ReloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ParamsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NmsThreshold        float32                `protobuf:"fixed32,1,opt,name=nms_threshold,json=nmsThreshold,proto3" json:"nms_threshold,omitempty"`
	ConfidenceThreshold float32                `protobuf:"fixed32,2,opt,name=confidence_threshold,json=confidenceThreshold,proto3" json:"confidence_threshold,omitempty"`
	EntropyThreshold    float32                `protobuf:"fixed32,3,opt,name=entropy_threshold,json=entropyThreshold,proto3" json:"entropy_threshold,omitempty"`
	W1                  float32                `protobuf:"fixed32,4,opt,name=w1,proto3" json:"w1,omitempty"`
	W2                  float32                `protobuf:"fixed32,5,opt,name=w2,proto3" json:"w2,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ParamsRequest) Reset() {
	*x = ParamsRequest{}
	mi := &file_detection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamsRequest) ProtoMessage() {}

func (x *ParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamsRequest.ProtoReflect.Descriptor instead.
func (*ParamsRequest) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{7}
}

func (x *ParamsRequest) GetNmsThreshold() float32 {
	if x != nil {
		return x.NmsThreshold
	}
	return 0
}

func (x *ParamsRequest) GetConfidenceThreshold() float32 {
	if x != nil {
		return x.ConfidenceThreshold
	}
	return 0
}

func (x *ParamsRequest) GetEntropyThreshold() float32 {
	if x != nil {
		return x.EntropyThreshold
	}
	return 0
}

func (x *ParamsRequest) GetW1() float32 {
	if x != nil {
		return x.W1
	}
	return 0
}

func (x *ParamsRequest) GetW2() float32 {
	if x != nil {
		return x.W2
	}
	return 0
}

type ParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamsResponse) Reset() {
	*x = ParamsResponse{}
	mi := &file_detection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamsResponse) ProtoMessage() {}

func (x *ParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamsResponse.ProtoReflect.Descriptor instead.
func (*ParamsResponse) Descriptor() ([]byte, []int) {
	return file_detection_proto_rawDescGZIP(), []int{8}
}

func (x *ParamsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ParamsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_detection_proto protoreflect.FileDescriptor

const file_detection_proto_rawDesc = "" +
	"\n" +
	"\x0fdetection.proto\x12\tdetection\"I\n" +
	"\x12BatchDetectRequest\x12\x16\n" +
	"\x06images\x18\x01 \x03(\fR\x06images\x12\x1b\n" +
	"\tframe_ids\x18\x02 \x03(\x03R\bframeIds\"J\n" +
	"\x13BatchDetectResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.detection.DetectResponseR\aresults\"@\n" +
	"\rDetectRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\x03R\aframeId\"\xdc\x01\n" +
	"\x0eDetectResponse\x12)\n" +
	"\x10visualized_image\x18\x01 \x01(\fR\x0fvisualizedImage\x12%\n" +
	"\x0eoriginal_image\x18\x02 \x01(\fR\roriginalImage\x128\n" +
	"\n" +
	"detections\x18\x03 \x03(\v2\x18.detection.DetectionMetaR\n" +
	"detections\x12#\n" +
	"\rhas_uncertain\x18\x04 \x01(\bR\fhasUncertain\x12\x19\n" +
	"\bframe_id\x18\x05 \x01(\x03R\aframeId\"\x8b\x02\n" +
	"\rDetectionMeta\x12\x0e\n" +
	"\x02x1\x18\x01 \x01(\x02R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x02 \x01(\x02R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x03 \x01(\x02R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x04 \x01(\x02R\x02y2\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12\x19\n" +
	"\bclass_id\x18\x06 \x01(\x05R\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\a \x01(\tR\tclassName\x12!\n" +
	"\fis_uncertain\x18\b \x01(\bR\visUncertain\x12\x18\n" +
	"\aentropy\x18\t \x01(\x02R\aentropy\x12#\n" +
	"\ranomaly_score\x18\n" +
	" \x01(\x02R\fanomalyScore\".\n" +
	"\rReloadRequest\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\"D\n" +
	"\x0eReloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb4\x01\n" +
	"\rParamsRequest\x12#\n" +
	"\rnms_threshold\x18\x01 \x01(\x02R\fnmsThreshold\x121\n" +
	"\x14confidence_threshold\x18\x02 \x01(\x02R\x13confidenceThreshold\x12+\n" +
	"\x11entropy_threshold\x18\x03 \x01(\x02R\x10entropyThreshold\x12\x0e\n" +
	"\x02w1\x18\x04 \x01(\x02R\x02w1\x12\x0e\n" +
	"\x02w2\x18\x05 \x01(\x02R\x02w2\"D\n" +
	"\x0eParamsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa8\x02\n" +
	"\x10DetectionService\x12=\n" +
	"\x06Detect\x12\x18.detection.DetectRequest\x1a\x19.detection.DetectResponse\x12L\n" +
	"\vBatchDetect\x12\x1d.detection.BatchDetectRequest\x1a\x1e.detection.BatchDetectResponse\x12B\n" +
	"\vReloadModel\x12\x18.detection.ReloadRequest\x1a\x19.detection.ReloadResponse\x12C\n" +
	"\fUpdateParams\x12\x18.detection.ParamsRequest\x1a\x19.detection.ParamsResponseB9Z7anomaly_detection_system/backend/internal/grpcclient/pbb\x06proto3"

var (
	file_detection_proto_rawDescOnce sync.Once
	file_detection_proto_rawDescData []byte
)

func file_detection_proto_rawDescGZIP() []byte {
	file_detection_proto_rawDescOnce.Do(func() {
		file_detection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_detection_proto_rawDesc), len(file_detection_proto_rawDesc)))
	})
	return file_detection_proto_rawDescData
}

var file_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_detection_proto_goTypes = []any{
	(*BatchDetectRequest)(nil),  // 0: detection.BatchDetectRequest
	(*BatchDetectResponse)(nil), // 1: detection.BatchDetectResponse
	(*DetectRequest)(nil),       // 2: detection.DetectRequest
	(*DetectResponse)(nil),      // 3: detection.DetectResponse
	(*DetectionMeta)(nil),       // 4: detection.DetectionMeta
	(*ReloadRequest)(nil),       // 5: detection.ReloadRequest
	(*ReloadResponse)(nil),      // 6: detection.ReloadResponse
	(*ParamsRequest)(nil),       // 7: detection.ParamsRequest
	(*ParamsResponse)(nil),      // 8: detection.ParamsResponse
}
var file_detection_proto_depIdxs = []int32{
	3, // 0: detection.BatchDetectResponse.results:type_name -> detection.DetectResponse
	4, // 1: detection.DetectResponse.detections:type_name -> detection.DetectionMeta
	2, // 2: detection.DetectionService.Detect:input_type -> detection.DetectRequest
	0, // 3: detection.DetectionService.BatchDetect:input_type -> detection.BatchDetectRequest
	5, // 4: detection.DetectionService.ReloadModel:input_type -> detection.ReloadRequest
	7, // 5: detection.DetectionService.UpdateParams:input_type -> detection.ParamsRequest
	3, // 6: detection.DetectionService.Detect:output_type -> detection.DetectResponse
	1, // 7: detection.DetectionService.BatchDetect:output_type -> detection.BatchDetectResponse
	6, // 8: detection.DetectionService.ReloadModel:output_type -> detection.ReloadResponse
	8, // 9: detection.DetectionService.UpdateParams:output_type -> detection.ParamsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_detection_proto_init() }
func file_detection_proto_init() {
	if File_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_detection_proto_rawDesc), len(file_detection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_detection_proto_goTypes,
		DependencyIndexes: file_detection_proto_depIdxs,
		MessageInfos:      file_detection_proto_msgTypes,
	}.Build()
	File_detection_proto = out.File
	file_detection_proto_goTypes = nil
	file_detection_proto_depIdxs = nil
}
