# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65tection.proto\x12\tdetection\"0\n\rDetectRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\x03\"\x99\x01\n\x0e\x44\x65tectResponse\x12\x18\n\x10visualized_image\x18\x01 \x01(\x0c\x12\x16\n\x0eoriginal_image\x18\x02 \x01(\x0c\x12,\n\ndetections\x18\x03 \x03(\x0b\x32\x18.detection.DetectionMeta\x12\x15\n\rhas_uncertain\x18\x04 \x01(\x08\x12\x10\n\x08\x66rame_id\x18\x05 \x01(\x03\"\xb7\x01\n\rDetectionMeta\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x06 \x01(\x05\x12\x12\n\nclass_name\x18\x07 \x01(\t\x12\x14\n\x0cis_uncertain\x18\x08 \x01(\x08\x12\x0f\n\x07\x65ntropy\x18\t \x01(\x02\x12\x15\n\ranomaly_score\x18\n \x01(\x02\"#\n\rReloadRequest\x12\x12\n\nmodel_path\x18\x01 \x01(\t\"2\n\x0eReloadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"w\n\rParamsRequest\x12\x15\n\rnms_threshold\x18\x01 \x01(\x02\x12\x1c\n\x14\x63onfidence_threshold\x18\x02 \x01(\x02\x12\x19\n\x11\x65ntropy_threshold\x18\x03 \x01(\x02\x12\n\n\x02w1\x18\x04 \x01(\x02\x12\n\n\x02w2\x18\x05 \x01(\x02\"2\n\x0eParamsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xda\x01\n\x10\x44\x65tectionService\x12=\n\x06\x44\x65tect\x12\x18.detection.DetectRequest\x1a\x19.detection.DetectResponse\x12\x42\n\x0bReloadModel\x12\x18.detection.ReloadRequest\x1a\x19.detection.ReloadResponse\x12\x43\n\x0cUpdateParams\x12\x18.detection.ParamsRequest\x1a\x19.detection.ParamsResponseB9Z7anomaly_detection_system/backend/internal/grpcclient/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7anomaly_detection_system/backend/internal/grpcclient/pb'
  _globals['_DETECTREQUEST']._serialized_start=30
  _globals['_DETECTREQUEST']._serialized_end=78
  _globals['_DETECTRESPONSE']._serialized_start=81
  _globals['_DETECTRESPONSE']._serialized_end=234
  _globals['_DETECTIONMETA']._serialized_start=237
  _globals['_DETECTIONMETA']._serialized_end=420
  _globals['_RELOADREQUEST']._serialized_start=422
  _globals['_RELOADREQUEST']._serialized_end=457
  _globals['_RELOADRESPONSE']._serialized_start=459
  _globals['_RELOADRESPONSE']._serialized_end=509
  _globals['_PARAMSREQUEST']._serialized_start=511
  _globals['_PARAMSREQUEST']._serialized_end=630
  _globals['_PARAMSRESPONSE']._serialized_start=632
  _globals['_PARAMSRESPONSE']._serialized_end=682
  _globals['_DETECTIONSERVICE']._serialized_start=685
  _globals['_DETECTIONSERVICE']._serialized_end=903
# @@protoc_insertion_point(module_scope)
